- id: 1
  title: Asesoría
  description: Apoyo y práctica de un tema en el que se explica y se resuelven dudas de alguna asignatura de español, lengua materna, conocimiento del medio, matemáticas, ciencias naturales, historia, geografía o formación cívica y ética.<br><br>Sesión activa y dinámica en donde se incluyen ejercicios y material de apoyo, además del uso de pizarrón, videos y juegos para mejor entendimiento y práctica del tema.<br><br>Sesión de 60 minutos
  image: /assets/images/cappuccino.jpg
  price: 300
  weight: 0
  maximum-quantity: 0
  category: Educación básica
#  url: https://dragonfruit.jekyll-themes.com #URL of the page where the product is present

- id: 2
  title: Clases particulares
  description: Explicación y práctica, resolver dudas sobre algún tema relacionado con las asignaturas de primaria: español, lengua materna, conocimiento del medio, matemáticas, ciencias naturales, historia, geografía o formación cívica y ética.<br><br>Sesión activa y dinámica en donde se incluyen ejercicios y material de apoyo, además del uso de pizarrón, videos y juegos para mejor entendimiento y práctica del tema.<br><br>3 Sesiones de 60 minutos
  image: /assets/images/espresso.jpg
  price: 750
  weight: 0
  maximum-quantity: 0
  category: Educación básica


- id: 3
  title: Mocha
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/black-coffee.jpg
  price: 2.59
  weight: 100
  maximum-quantity: 3
  category: coffee

- id: 4
  title: Oolong Tea
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/justin-leibow-62-unsplash.jpg
  price: 3.99
  weight: 100
  maximum-quantity: 5
  category: tea

- id: 5
  title: Black Tea
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/drew-taylor-235558-unsplash.jpg
  price: 4.19
  weight: 100
  maximum-quantity: 5
  category: tea

- id: 6
  title: Fruit Tea
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/erol-ahmed-305920-unsplash.jpg
  price: 4.59
  weight: 100
  maximum-quantity: 5
  category: tea

- id: 7
  title: Ice Tea
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/paul-hanaoka-280205-unsplash.jpg
  price: 4.99
  weight: 200
  maximum-quantity: 5
  category: tea
